<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addclientjwks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('client', 'jwks', 'string', null,
            array(
                'type' => 'string',
                'fixed' => false,
                'unsigned' => false,
                'primary' => false,
                'notnull' => false,
                'autoincrement' => false,
                'length' => NULL
            )
        );

    }

    public function down()
    {
        $this->removeColumn('client', 'jwks');
    }
}